### ISSUE TITLE
Live version broken?

### ISSUE THREAD

**Issue by henfri** [KimNyholm/tasmota-device-locator#34]
Hi,

the live version for me redirects to http://ww25.tasmota.simplethings.work/?subid1=20230509-0611-2608-8233-d39e00714de6

This shows me only some ads. 

Can you check, please?

Regards,
Hendrik

**Comment by KimNyholm** [comment]
Hi Hendrik
The domain simplethings.work has been taken over by others, and the above live link is is no longer valid.
I have removed the reference to the live server from the readme.
Please feel free to fork the code and establish an other server.
Regards
Kim

**Comment by henfri** [comment]
Thanks Kim.
I am lacking the skills, though
