### ISSUE TITLE
http://tasmota.simplethings.work/ is down

### ISSUE THREAD

**Issue by Jason2866** [KimNyholm/tasmota-device-locator#4]
No text

**Comment by KimNyholm** [comment]
Usage of http://tasmota.simplethings.work/ was low and I decided to down the server.
I have removed the reference to the live server from the readme.
Please feel free to fork the code and establish an other server.

**Comment by kiwichrish** [comment]
Thanks for running that while you were though, I had it bookmarked and used it every now and then. :-)
